### ISSUE TITLE
Sticky navbar

### ISSUE THREAD

**Issue by maackle** [ActivityWatch/aw-webui#299]
It would be convenient for the navbar to always be present at the top of the window to prevent unneeded scrolling for tall pages.

The following additional CSS accomplishes this pretty well for desktop. Not sure how it works on mobile.

```css
nav.navbar {
    position: fixed;
    top: 0;
    width: 100%;
    z-index: 1;
}

/* the main container (may want to add extra specificity) */
.container {
    margin-top: 70px;
}
```
